/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWardsRouteImport } from './routes/_app/wards'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSystemSettingsRouteImport } from './routes/_app/system-settings'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppShiftHistoryRouteImport } from './routes/_app/shift-history'
import { Route as AppShiftRouteImport } from './routes/_app/shift'
import { Route as AppRotaRouteImport } from './routes/_app/rota'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppLocumRouteImport } from './routes/_app/locum'
import { Route as AppLeaveEntitlementsRouteImport } from './routes/_app/leave-entitlements'
import { Route as AppLeaveRouteImport } from './routes/_app/leave'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWardsRoute = AppWardsRouteImport.update({
  id: '/wards',
  path: '/wards',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemSettingsRoute = AppSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftHistoryRoute = AppShiftHistoryRouteImport.update({
  id: '/shift-history',
  path: '/shift-history',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftRoute = AppShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AppRoute,
} as any)
const AppRotaRoute = AppRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLocumRoute = AppLocumRouteImport.update({
  id: '/locum',
  path: '/locum',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveEntitlementsRoute = AppLeaveEntitlementsRouteImport.update({
  id: '/leave-entitlements',
  path: '/leave-entitlements',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/leave': typeof AppLeaveRoute
  '/leave-entitlements': typeof AppLeaveEntitlementsRoute
  '/locum': typeof AppLocumRoute
  '/reports': typeof AppReportsRoute
  '/rota': typeof AppRotaRoute
  '/shift': typeof AppShiftRoute
  '/shift-history': typeof AppShiftHistoryRoute
  '/staff': typeof AppStaffRoute
  '/system-settings': typeof AppSystemSettingsRoute
  '/users': typeof AppUsersRoute
  '/wards': typeof AppWardsRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/leave': typeof AppLeaveRoute
  '/leave-entitlements': typeof AppLeaveEntitlementsRoute
  '/locum': typeof AppLocumRoute
  '/reports': typeof AppReportsRoute
  '/rota': typeof AppRotaRoute
  '/shift': typeof AppShiftRoute
  '/shift-history': typeof AppShiftHistoryRoute
  '/staff': typeof AppStaffRoute
  '/system-settings': typeof AppSystemSettingsRoute
  '/users': typeof AppUsersRoute
  '/wards': typeof AppWardsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/leave': typeof AppLeaveRoute
  '/_app/leave-entitlements': typeof AppLeaveEntitlementsRoute
  '/_app/locum': typeof AppLocumRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/rota': typeof AppRotaRoute
  '/_app/shift': typeof AppShiftRoute
  '/_app/shift-history': typeof AppShiftHistoryRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/system-settings': typeof AppSystemSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/wards': typeof AppWardsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/approvals'
    | '/audit'
    | '/leave'
    | '/leave-entitlements'
    | '/locum'
    | '/reports'
    | '/rota'
    | '/shift'
    | '/shift-history'
    | '/staff'
    | '/system-settings'
    | '/users'
    | '/wards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/approvals'
    | '/audit'
    | '/leave'
    | '/leave-entitlements'
    | '/locum'
    | '/reports'
    | '/rota'
    | '/shift'
    | '/shift-history'
    | '/staff'
    | '/system-settings'
    | '/users'
    | '/wards'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/_app/approvals'
    | '/_app/audit'
    | '/_app/leave'
    | '/_app/leave-entitlements'
    | '/_app/locum'
    | '/_app/reports'
    | '/_app/rota'
    | '/_app/shift'
    | '/_app/shift-history'
    | '/_app/staff'
    | '/_app/system-settings'
    | '/_app/users'
    | '/_app/wards'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wards': {
      id: '/_app/wards'
      path: '/wards'
      fullPath: '/wards'
      preLoaderRoute: typeof AppWardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-settings': {
      id: '/_app/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof AppSystemSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shift-history': {
      id: '/_app/shift-history'
      path: '/shift-history'
      fullPath: '/shift-history'
      preLoaderRoute: typeof AppShiftHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shift': {
      id: '/_app/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof AppShiftRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rota': {
      id: '/_app/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof AppRotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locum': {
      id: '/_app/locum'
      path: '/locum'
      fullPath: '/locum'
      preLoaderRoute: typeof AppLocumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-entitlements': {
      id: '/_app/leave-entitlements'
      path: '/leave-entitlements'
      fullPath: '/leave-entitlements'
      preLoaderRoute: typeof AppLeaveEntitlementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave': {
      id: '/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppLeaveEntitlementsRoute: typeof AppLeaveEntitlementsRoute
  AppLocumRoute: typeof AppLocumRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRotaRoute: typeof AppRotaRoute
  AppShiftRoute: typeof AppShiftRoute
  AppShiftHistoryRoute: typeof AppShiftHistoryRoute
  AppStaffRoute: typeof AppStaffRoute
  AppSystemSettingsRoute: typeof AppSystemSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWardsRoute: typeof AppWardsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppLeaveEntitlementsRoute: AppLeaveEntitlementsRoute,
  AppLocumRoute: AppLocumRoute,
  AppReportsRoute: AppReportsRoute,
  AppRotaRoute: AppRotaRoute,
  AppShiftRoute: AppShiftRoute,
  AppShiftHistoryRoute: AppShiftHistoryRoute,
  AppStaffRoute: AppStaffRoute,
  AppSystemSettingsRoute: AppSystemSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppWardsRoute: AppWardsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
